name: unicons
description: 1000+ beautiful icons to use in you dream project, with all the customization Flutter provides
# author: Pedro Lemos <lemozxpedro@gmail.com>
homepage: https://github.com/pedrolemoz/unicons-flutter

version: 2.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.2

  flutter_lints: ^2.0.0
  fontify: ^0.3.0-nullsafety.1

flutter:
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: UniconsLine
      fonts:
        - asset: icons/UniconsLine.ttf
    
    - family: UniconsSolid
      fonts:
        - asset: icons/UniconsSolid.ttf

    - family: UniconsThinline
      fonts:
        - asset: icons/UniconsThinline.ttf

    - family: UiIcons
      fonts:
        - asset: assets/fonts/ui_icons.ttf

fontify:
  input_svg_dir: "icons/"
  output_font_file: "assets/fonts/ui_icons.ttf"
  output_class_file: "lib/fonts/ui_icons.dart"
  class_name: "UiIcons"
  font_name: "UiIcons"
  indent: 2
  package: 
  normalize: true
  ignore_shapes: true
  recursive: true
  verbose: false